development:
  adapter:  postgresql
  host:     localhost
  port:     5432
  database: sirocco_development
  username: Sirocco
  password: MultiSync1

test:
  adapter:  postgresql
  host:     localhost
  port:     5432
  database: sirocco_test
  username: Sirocco
  password: MultiSync1

production:
